# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-14 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.IntegerField(default=0)),
                ('groupname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('codechef', models.CharField(max_length=50)),
                ('codeforces', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=0)),
                ('groupid', models.ManyToManyField(blank=True, to='programming.Groups')),
            ],
        ),
    ]
