# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='codechefdetails',
            field=models.TextField(blank=True),
        ),
    ]
