# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-20 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0002_student_details_codechefdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
