# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0002_student_details_codechefdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='groupname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
