# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0003_auto_20180719_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='name',
            field=models.CharField(error_messages={'unique': 'Already Exists!'}, max_length=50, unique=True),
        ),
    ]
