# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-21 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0004_auto_20180719_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='codeforcesdetails',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='groupname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
