# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0005_auto_20180721_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='codechefrating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student_details',
            name='codeforcesrating',
            field=models.IntegerField(default=0),
        ),
    ]
