# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-27 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0007_remove_groups_groupid'),
        ('programming', '0003_student_details_rating'),
    ]

    operations = [
    ]
