# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0007_remove_groups_groupid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probname', models.CharField(max_length=100)),
            ],
        ),
    ]
