# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-27 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0008_merge_20180727_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='rating',
        ),
    ]
