# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-02 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0008_dailychallenges'),
        ('programming', '0009_remove_student_details_rating'),
    ]

    operations = [
    ]
