# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-18 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0010_merge_20180802_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychallenges',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
